### ISSUE TITLE
[WIP] Migrate to Java11

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-case#9]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Java 8 is used.

* **What is the expected behavior?**
Last LTS Java version is 11, so there is no reason not to use it.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by AbdelHedhili** [comment]
#25 merged
